# Generated by Django 2.2.7 on 2019-11-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cocktailingredientunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailingredientunit',
            name='ingredient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktailingredientunit',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Unit'),
        ),
        migrations.AlterField(
            model_name='cocktailingredientunit',
            name='cocktail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cocktail'),
        ),
    ]
