# Generated by Django 2.2.7 on 2019-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191115_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='recipe',
            field=models.TextField(blank=True, default=True),
        ),
    ]
